language: node_js

cache:
  directories:
  - node_modules

node_js:
  - '8'

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - google-chrome-stable
        firefox: 'latest-esr'
    - os: osx
    - os: windows

before_install:
  - ./tools/travis-setup.sh

script:
  - yarn ci-check

after_success:
  - yarn semantic-release

notifications:
  email: false
